

BUT_TOP_LEFT = 2
BUT_TOP_CENTER = 1
BUT_TOP_RIGHT = 0
BUT_MID_LEFT = 3
BUT_MID_CENTER = 4
BUT_MID_RIGHT = 5
BUT_BOT_LEFT = 8
BUT_BOT_CENTER = 7
BUT_BOT_RIGHT = 6


BUT_PLAYPAUSE = BUT_MID_CENTER
BUT_ENTER = BUT_MID_CENTER

BUT_SOURCE = BUT_TOP_LEFT
BUT_LIST = BUT_TOP_LEFT

BUT_UP = BUT_TOP_CENTER
BUT_DOWN = BUT_BOT_CENTER

BUT_LEFT = BUT_MID_LEFT
BUT_PREVIOUS = BUT_MID_LEFT

BUT_RIGHT = BUT_MID_RIGHT
BUT_NEXT = BUT_MID_RIGHT

BUT_STOP = BUT_BOT_RIGHT

BUT_QUEUE = BUT_TOP_RIGHT


SRC_ITEMS = (
    "TT_SRC_ITEM_LOCAL_STORAGE",
    "TT_SRC_ITEM_CD",
    "TT_SRC_ITEM_INTERNET_RADIO",
    "TT_SRC_ITEM_PODCASTS",
)
